version: 2
registries:
  nuget-feed-default:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
    
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly

- package-ecosystem: npm
  directory: "/Source/Blazorise"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Blazorise.AntDesign"
  schedule:
    interval: daily
   
- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.Charts"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.Charts.DataLabels"
  schedule:
    interval: daily
    
- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.Charts.Streaming"
  schedule:
    interval: daily
